"""Labeled retrieval dataset (docs/17 acceptance #5): 22 operator-phrased
queries hand-labeled with the relevant seed runbooks. The unit of relevance
is the document — chunking strategies compete on surfacing the right doc,
which is exactly what the comparison measures.
"""
from __future__ import annotations

# (query, relevant doc ids)
LABELED_QUERIES: list[tuple[str, list[str]]] = [
    ("pods getting OOMKilled after a deployment",
     ["runbook-oom", "runbook-rollback"]),
    ("how should I size a database connection pool",
     ["runbook-conn-pool"]),
    ("p99 latency spiked right after a release",
     ["runbook-latency", "runbook-rollback"]),
    ("roll back a bad deploy to the previous revision",
     ["runbook-rollback"]),
    ("TLS handshake failures and SSL errors in client logs",
     ["runbook-cert"]),
    ("certificate expired what do I do",
     ["runbook-cert"]),
    ("intermittent DNS lookup timeouts across many services",
     ["runbook-dns"]),
    ("CoreDNS pods restarting and name resolution errors",
     ["runbook-dns"]),
    ("node disk full and pods being evicted",
     ["runbook-disk"]),
    ("kubelet eviction storm from disk pressure",
     ["runbook-disk"]),
    ("what are the canary rollout stages and abort rules",
     ["runbook-canary"]),
    ("can I promote a canary manually",
     ["runbook-canary"]),
    ("deploying during a change freeze window",
     ["runbook-freeze"]),
    ("break-glass exception during a freeze",
     ["runbook-freeze"]),
    ("who gets paged for a SEV1 outage",
     ["runbook-escalation"]),
    ("when should automation escalate to a human",
     ["runbook-escalation"]),
    ("memory limit exceeded container killed",
     ["runbook-oom"]),
    ("connection pool increase caused memory exhaustion",
     ["runbook-conn-pool", "runbook-oom"]),
    ("garbage collection pauses raising tail latency",
     ["runbook-latency"]),
    ("open a revert PR after rolling back",
     ["runbook-rollback"]),
    ("error rate SLO breach during rollout",
     ["runbook-canary"]),
    ("investigate what changed before a latency regression",
     ["runbook-latency"]),
]
